# Generated by Django 5.0.2 on 2024-02-17 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pgs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pg_name', models.CharField(max_length=100)),
                ('pg_address', models.CharField(max_length=500)),
                ('pg_cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=200)),
                ('profession', models.CharField(choices=[('Student', 'Student'), ('Job', 'Job')], max_length=300)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=100)),
                ('Adhar_card', models.FileField(upload_to='')),
                ('Photo', models.ImageField(upload_to='')),
                ('pg_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.pgs')),
            ],
        ),
    ]
